### ISSUE TITLE
Error: PNG file appears to be corrupted by text file conversions

### ISSUE THREAD

**Issue by baikon** [angular-fullstack/generator-angular-fullstack#1382]
Using angular fullstack v2.1.1

The build seems to be hanging up when hitting imagemin. What's new is when I commit images to github, it shoots a crlf to lf warning too.

Anyone run into this as well?

**Comment by Awk34** [comment]
make sure your `.gitattributes` looks something like https://github.com/DaftMonk/generator-angular-fullstack/blob/master/app/templates/.gitattributes

**Comment by baikon** [comment]
That is the answer. Thank you good sir.

**Comment by harelba** [comment]
Hi,

I've struggled with the same issue, and it does seem related to the way git handles line ending translation on each checkout.

Two questions:
1. What was the reason for adding the .gitattributes with ````* text eol=lf```` in the first place? In many other cases I've seen, there's no need for it in the first place.
2. If for some reason, the fie is needed, wouldn't it be better if the generator would create the more specific definitions? For example, if it's a specific file that needs lf line endings, then just define the relevant files there, and leave everything else as auto, or at least add the *.png and such to the file.

WDYT?

**Comment by Awk34** [comment]
@harelba Yeah specific text definitions would be better. I just haven't gotten around to it. A PR would be welcome.

**Comment by harelba** [comment]
@Awk34 I'd be glad to send a PR for this. However, my own solution was to eventually remove .gitattributes altogether, and change the global core.autocrlf flag to false before checking out, so multi-platform checkouts would work well (I actually had to delete my entire git repository, since the original image data there was corrupted, and the "modified" check of ````git status```` was thrown off by this as well).

Do you happen to know what was the original reason for adding the .gitattributes file? At first I was under the impression that it's needed for one of the configuration files, at least for now, it seems that things are working fully well without it.

Harel

**Comment by harelba** [comment]
@Awk34 I'm missing something - This change seems to have been already added at Sep 6 in b8255857e83ffc913d67cbcf9178c36fe94570fb to the master.

Sorry if this is a silly question, but is there a need for an additional PR on this matter? I'd be glad to do it if the answer is yes.

Harel

**Comment by Awk34** [comment]
It would probably be better to mark specific files (js, html, css, etc) as text with `lf` endings, instead of everything except for those four image types
