### ISSUE TITLE
New EventEmitter vs Traditional

### ISSUE THREAD

**Issue by dolanmiu** [angular-fullstack/generator-angular-fullstack#1383]
In later versions of `generator-angular-fullstack`, the socket.io uses an EventEmitter

```
var EventEmitter = require('events').EventEmitter;
var ItemEvents = new EventEmitter();

...
```

What is the advantage of this over the traditional `v2.x.x` approach of;

```
function onSave(socket, doc, cb) {
    Crate.populate(doc, {
        path: 'inventory.item'
    }, function (err, crate) {
        socket.emit('crate:save', crate);
    });
}

function onRemove(socket, doc, cb) {
    socket.emit('crate:remove', doc);
}

exports.register = function (socket) {
    Crate.schema.post('save', function (doc) {
        onSave(socket, doc);
    });
    Crate.schema.post('remove', function (doc) {
        onRemove(socket, doc);
    });
};
```

I prefer the traditional old style, it is much simpler, much less code. Seems like to me EventEmitter adds double the lines of code for LITERALLY the exact same end result.

Opinions?

**Comment by madhab452** [comment]
i was stuck in populating model data on save events. thanks to your code that really save my hours.

**Comment by aabm00** [comment]
+1

**Comment by kingcody** [comment]
The original intent in implementing the native node `EventEmitter` library was to give the project base a consistent way of handling model events across different ORM's such Mongoose or Sequelize. Another reason was, the node eventEmitter API is very prolific and should make additional integrations with libraries easier; due to examples and blog posts being highly available.
