### ISSUE TITLE
Example of Relational Modeling with Mongoose within this framework

### ISSUE THREAD

**Issue by lukeqi** [angular-fullstack/generator-angular-fullstack#1433]
This project is very cool, but the example project covers only single unconnected models.

In real scenario, we have posts, and posts have comments, which are issued by users.

The Endpoint Generator is very good, but how about adding the generation mode for related models?

I am not familiar with mongoose implementing related models. If someone can provide the mongoose related models implementation within this framework, it will be even better.

So, anyone can guide me on how to set up the related models with Mongoose within this framework? 

Thank you very much!

**Comment by lukeqi** [comment]
I find a solution here:
https://alexanderzeitler.com/articles/mongoose-referencing-schema-in-properties-and-arrays/
https://github.com/AlexZeitler/mongoose-schema-reference-sample

Any other suggestions?

**Comment by sandorTuranszky** [comment]
Rather than using ref, better architect you db structure using nesting. It is advisable to switch from relational way of thinking when using NoSQL.

**Comment by Koslun** [comment]
Don't have a link to a specific blog post or similar to backup my claim. But would suggest constructing your indexes and models after how you will access them. If you need both of the two objects every time, or at least in the majority of cases, then nesting might thus be a good option. 

If however you figure that you'll only need one or the other ref might again be the best option.

Either way I'd remind you that regular mongoose documents can only hold 16 MB and that gathering a referenced model, or populating a document is the same as an equivalent db query. While multiple levels of references is quoted as an anti-pattern on many places. It is also not non-trival to perform several layers of population.

Searching on an indexed query is further something like a O(log(n)) operation while non-indexed becomes O(n). Meaning you might want to prefer mainly doing searches on easily indexable queries.

**Comment by sandorTuranszky** [comment]
Hard to think of any special requirements for a blog, but in general a blog comprises:
- user/author, who has posts -  1:M relation
- a post has comments 1:M relation
- user/author has multiple comments in multiple posts: 1:M relation

The suggestion is to nest posts in user schema. And comments in posts schema. Because a post can not have multiple users and a comment can to have multiple posts.

User/author schema
...
posts: []
...

Comments schema
_id: comment's author username
...

Getting a post will automatically return all comments. And you will have comment's author username to display with the comment. This is a very primitive representation just to show how this can be done by nesting.

I alway manage to do relations using nesting. Sometimes it is a trade off but that is the price you pay for very fast queries. 

I suggest that you look into a MongodDB university course on MongoDB. Btw. they are building a blog as a task during the course and they discuss relations. This will help you for sure. 
This one is for node js developers https://university.mongodb.com/courses/M101JS/about

**Comment by lukeqi** [comment]
Hi @sandorTuranszky @Koslun ,

Thank you for your solution on this issue ! Yeah I think I should switch my mind from the relational DB to "NoSQL" DB.

For the Posts - Comments - Users case, I agree that the posts should hold the comments, as they need the latter in virtually all time.

According to what I have linked and @sandorTuranszky , below :  

    var PostSchema = new mongoose.Schema({
        title: String,
        postedBy: {
            type: mongoose.Schema.Types.ObjectId,
            ref: 'User'
        },
       comments: [{
            text: String,
            postedBy: {
                type: mongoose.Schema.Types.ObjectId,
                ref: 'User'
            }
        }]
    });

might be the ultimate / better solution.

As Posts - Comments - Users case is an essential scenario for most modern websites, I seriously suggest that this very module to be included in every popular framework's example project, like this one. : )

**Comment by sandorTuranszky** [comment]
It really depends on you data access pattern. But what you have to keep in mind is performance and you can create a dummy db and test performance with indexes. If it works for, than you are on the right track.

**Comment by lukeqi** [comment]
Yes +1, we should test it in real scenarios

**Comment by Koslun** [comment]
For each of those comments you would still need to populate user objects into them. I wonder if this doesn't actually mean that you do that many user queries.

I would also consider an alternative implementation of just embedding either the email or user name of the user instead and possibly more, preferably immutable, fields. Fields such as when the user created the account. Immutable because if the user can actually change this field then you have to update this whenever the user changes it.

Would also be prudent to add an index to one of the user fields that you display if you want to be able to get more information. 

So definitely not a strictly better alternative as adding indexes increases write time of each user while embedding fields in other documents creates increased complexity when the user changes these fields. Though you would skip some of the population of users for these posts which would reduce complexity a little bit as well.

Essentially agree with @sandorTuranszky on that you're best off just measuring performance and see what works best.

@lukeqi I think this generator is also more for any kind of web app so don't necessarily think it's a universal thing that everyone needs comments + posts etc. But would perhaps be better to use that as a proof-of-concept rather than the current "things". Especially if there are developers who want to work on that rather than the more general gulp, grunt, typescript and testing scenarios.

**Comment by lukeqi** [comment]
Hi @Koslun ,
Thanks for the reply and it is really helpful! and I find this:

https://docs.mongodb.org/ecosystem/use-cases/storing-comments/

The official mongodb site has a discussion on how to save comments. It seems, however, if to achieve the max flexibility, using One Comment per Document would be the best choice. Do you agree?

**Comment by Awk34** [comment]
Closing as I believe this has been answered
