### ISSUE TITLE
Validation Error with Email: Even on new App generation

### ISSUE THREAD

**Issue by danogbuagu** [angular-fullstack/generator-angular-fullstack#1498]
Two validation errors, even while new application just been generated:
1) ValidationError: The specified email address is already in use.
2) ValidationError: Email cannot be blank

**Comment by Awk34** [comment]
I can't reproduce this. You definitely need to provide more details for me to know what the problem is. Which generator version? Node version? OS? etc.

**Comment by awwong1** [comment]
I had this same problem. From a generated project, I had to update the user.model.spec.js file like so:

```
  it('should fail when saving a duplicate user', function() {
    return user.saveAsync()
      .then(function() {
        var userDup = genUser();
        //return userDup.saveAsync();
        return User.create(userDup);
      }).should.be.rejected;
  });

  describe('#email', function() {
    it('should fail when saving without an email', function() {
      user.email = '';
      //return user.saveAsync().should.be.rejected;
      return User.create(user).should.be.rejected;
    });
  });
```

Look at this issue here:
https://github.com/Automattic/mongoose/issues/3669

**Comment by palfaro91** [comment]
Hello I am getting this same error. It happens when I try to update a user's email. The error response says "email cannot be blank" and it actually displays an email value so I can't figure out why it's throwing this error. 
If I comment that validation out then it throws the duplicate email error even though the email does not exist in the db.  
Using 
**node** v8.9.1
**mongoose** 4.1.2
**generator version** 4.2.2

validation code 
`UserSchema
  .path('email')
  .validate(function(email) {
    if(authTypes.indexOf(this.provider) !== -1) {
      return true;
    }
    return !!(email && email.length);
  }, 'Email cannot be blank');`

route controller 
`export function updateContact(req, res){
  if(req.body._id) {
    Reflect.deleteProperty(req.body, '_id');
  }
  let update = new User(req.body);
  let setUpdate = {
    $set: {
      email: update.email,
      phoneNumber: update.phoneNumber,
    }
  };
 
  return User.findByIdAndUpdate(req.params.id, setUpdate, {new:true, upsert:true, setDefaultsOnInsert:true, runValidators:true}).exec()
    .then( (user) => {
      return res.json(user);
    }).catch(validationError(res));
}`

I'm not sure what is wrong. Any help please??
