### ISSUE TITLE
Where to inject modules (specifically ngMessages)? [Question]

### ISSUE THREAD

**Issue by skstudios** [angular-fullstack/generator-angular-fullstack#1541]
Where do I inject these modules in the angular-fullstack structure? 
https://www.npmjs.com/package/angular-messages

Most specifically this part 

angular.module('myApp', [require('angular-messages')]);

I keep getting not found or spelled wrong every place I try.

(and having this same question for other modules)

I certainly googled this but didn't find any direct answer to this. (Anyone that can answer this question you'll save me many many headaches as I'm learning this)

**Comment by skstudios** [comment]
Nevermind... i found the issue ( ordering in the index.html file for the js)

**Comment by Awk34** [comment]
You can't just `require` things in code that gets run in the browser, since browsers don't support it. You would need to use a front-end package manager like Webpack/Browserify/etc. The generator currently doesn't support front-end package managers / bundlers, but they are planned to be supported in the near future.
