### ISSUE TITLE
New user document gets removed from users collection upon grunt serve

### ISSUE THREAD

**Issue by mbaljeetsingh** [angular-fullstack/generator-angular-fullstack#1545]
When i first run the app using grunt serve everything works fine, when i signup, the new user document is added to the users collection. But when i stop and run the server again (grunt serve). The record is deleted from the collection. Am i missing something?

**Comment by chinnichaitanya** [comment]
@mbaljeetsingh There is something called `seedDB` in `server/config/environment/development.js`
Make it `false`.

**Comment by Awk34** [comment]
@mbaljeetsingh  When running the app in `development` mode, we re-seed the database on every server restart. This is so that any time you change server code, you're always running it against a freshly seeded database, eliminating the possibility of using old data that has been tainted by older server code that you have since changed. This will not happen when running the server in `production` mode. As @chinnichaitanya stated, setting the `seedDB` option to false will disable re-seeding the database on every server restart.
