### ISSUE TITLE
Missing `thing` route

### ISSUE THREAD

**Issue by amejiarosario** [angular-fullstack/generator-angular-fullstack#1614]
I'm trying out a brand new project created with `v3.3.0`, following the minimum versions guidelines for (yo, npm, node, ...) and its missing the `thing` route and it's making the test fail.

**Comment by amejiarosario** [comment]
@Awk34 @kingcody I have a PR for the missing route

**Comment by Awk34** [comment]
@amejiarosario I remember we *used* to have that line in (as well as the `thing` line for socket.io`) but we removed it because the `thing` endpoint generator *should* be injecting those lines automatically and it would cause issues having those `require`s twice. The solution is to figure out why the generator sometimes doesn't inject those lines.

**Comment by amejiarosario** [comment]
I see, @Awk34 I'm trying to start a new production project, but I'm having issues finding a stable version (all test and functionality works out of the box). What would you consider the most stable/tested version so far?

**Comment by Awk34** [comment]
@amejiarosario hard to say. I'll take any help I can get to iron out these small bugs.

**Comment by kingcody** [comment]
Hmm, this is interesting... @Awk34 have you been able to reproduce?

**Comment by Awk34** [comment]
@kingcody I have not

**Comment by Awk34** [comment]
#1591
