### ISSUE TITLE
What happened with JavaScript?

### ISSUE THREAD

**Issue by denebchorny** [angular-fullstack/generator-angular-fullstack#1627]
Hi sir,

Sorry for bother you, but What happened with JavaScript?.
I am using generator-angular-fullstack. When I'm creating a project with "yo angular-fullstack [app-name]" there isn't the option of Javascript (As before, previous YO versions), but only babel and typescript.

Thanks in advance.

**Comment by Awk34** [comment]
As of right now the code that the generator outputs with the Babel option is JavaScript. Babel is a transpiler that takes new JavaScript syntax and compiles it down to older, ECMAScript 5 syntax (Babel also has other options available). This is so that you can use most of the features of JavaScript that browsers / Node haven't implemented yet.
