### ISSUE TITLE
Getting $scope in Babel classes?

### ISSUE THREAD

**Issue by Kageetai** [angular-fullstack/generator-angular-fullstack#1651]
Hi there,
I really love your generator and have used the older versions for a while now, but with the change to Babel in the recent version I'm having some understanding problems, as I am totally new to Babel and ES6. Maybe you can help me out there. :)
The question is: How do I get the `$scope` in deeper nested functions etc.? One like this for example?
```javascript
 constructor($http, Locator) {
    
    this.markersEvents = {
      click: function (gMarker, eventName, model) {
        this.selEvent = model;
      }
    };
  }
```
I am running this inside the contructor of my Angular controller, but the line `this.selEvent = model;` doesn't work because `this` is not the scope of the controller anymore right?
So how do I access the usual `$scope` like without Babel?

Thanks,
Michael

**Comment by Awk34** [comment]
Things to research: 'Controller As' syntax, arrow functions, ES6 classes, the `this` binding

So for `controllerAs`, instead of looking for properties on the injected `$scope`, it looks for properties on the `new`ed class function. Every class function, and the class constructor, have the same `this` binding, but when you create a new function with the `function` keyword, it get it's own `this` binding. How can we retain the parent's `this`?

Keep it in a variable:
```js
class A {
  constructor() {
    var self = this;
    this.markersEvents = {
      click: function (gMarker, eventName, model) {
        self.selEvent = model;
      }
    };
  }
}
```
Bind the new function to the parent scope
```js
class A {
  constructor() {
    this.markersEvents = {
      click: function (gMarker, eventName, model) {
        this.selEvent = model;
      }.bind(this)
    };
  }
}
```
Use an arrow function
```js
class A {
  constructor() {
    this.markersEvents = {
      click: (gMarker, eventName, model) => {
        this.selEvent = model;
      }
    };
  }
}
```

**Comment by Kageetai** [comment]
Ah, thanks. That helps a lot. I guess I still have a lot to read up on the whole ES& shebang :)
