### ISSUE TITLE
OAUTH with Sequelize and Postgresql

### ISSUE THREAD

**Issue by smirciat** [angular-fullstack/generator-angular-fullstack#1654]
My setup chooses Sequelize for data modelling, and it is linked to a Postgresql database.  The scaffolding generated this portion of the user model in /server/api/user/user.model.js : 
```
provider: DataTypes.STRING,
    salt: DataTypes.STRING,
    facebook: DataTypes.TEXT,
    twitter: DataTypes.TEXT,
    google: DataTypes.TEXT,
    github: DataTypes.TEXT
```

To make Oauth work in this confirmation, I had to change the datatypes for facebook, google, twitter, and github to 
```
  twitter: DataTypes.JSON
```
.  Since the generator had already created the table model in Postgresq;, I had to either drop that table or manually alter it.  I assume this might cause problems with other Sequelize databases, since JSON is in Postgres but not some others.  Not sure if it would cause more harm then good to change the generator template in this manner, but it worked for my purpose.

Secondly, I had to manually modify each of the /server/auth/twitter/passport.js type files to match proper sequelize syntax.
```
function(token, tokenSecret, profile, done) {
    User.find({where: {
      'twitter.id_str': profile.id }
    })
```
in place of the original syntax (mongoose style)
```
function(token, tokenSecret, profile, done) {
    User.find({
      'twitter.id_str': profile.id 
    })
```

Hope this helps someone else!

**Comment by shaharyar123** [comment]
i am facing the OAUTH issue when i assign datatype **JSON** to facebook and google.  my database is mysql, getting this error : 


`Server failed to start due to error: SequelizeDatabaseError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'JSON, `twitter` JSON, `google` JSON, `provider` VARCHAR(255), `salt` VARCHAR(255' at line 1
`

 if i save it to type text or string then it works but i cant query on them. How to store in JSON datatype in MySql ?
