### ISSUE TITLE
[Warning] isAuthenticated runaway promise 

### ISSUE THREAD

**Issue by SkonTeam** [angular-fullstack/generator-angular-fullstack#1736]
So kept getting this warning whenever i hit the /api/users/me endpoint : 
`Warning: a promise was created in a handler but was not returned from it`

traced it back to "server/auth/auth.service.js" : 
``` javascript
export function isAuthenticated() {
 ...
    // Attach user to request
    .use(function(req, res, next) {
      User.findById(req.user._id).exec()
        .then(user => {
          if (!user) {
            return res.status(401).end();
          }
          req.user = user;
          next();
         //Not returning anything (aka undefined)
        })
        .catch(err => next(err));
    });
}
```

so i added a `return null;` and the warning disappeared.

``` javascript
export function isAuthenticated() {
 ...
    // Attach user to request
    .use(function(req, res, next) {
      User.findById(req.user._id).exec()
        .then(user => {
          if (!user) {
            return res.status(401).end();
          }
          req.user = user;
          next();
         return null;
        })
        .catch(err => next(err));
    });
}
```
Hope it helps someone.

**Comment by Awk34** [comment]
`User.findById(<ID>).exec()` creates a promise. That's the one it wants you to return.

**Comment by mjy78** [comment]
I believe the solution provided by @SkonTeam is correct. The warning is because Bluebird detects a Promise being returned from within the next() method down the express middleware chain (e.g. from a Sequelize call in an endpoint controller) and a subsequent call to `catch(err => next(err));`, so it warns that the promise chain is broken.

Either removing the catch or adding the `return null;` after `next();` resolves the issue, but I don't think we want to remove the call to catch.

See this thread for more info: https://github.com/sequelize/sequelize/issues/4883 The end result of the discussion there is to make the change that @SkonTeam is suggesting.

**Comment by mmmattos** [comment]
Great catch @SkonTeam. It saved me a few hours of trial and error....
Thanks a lot to all!
