### ISSUE TITLE
where should my static images go?

### ISSUE THREAD

**Issue by jspenc72** [angular-fullstack/generator-angular-fullstack#1754]
I have placed them in client/assets/images/

But when I run 
```bash
grunt build:dist
```
then they aren't showing up in the distribution version.

**Comment by renegadeds** [comment]
This is the correct location. For troubleshooting purposes, the following comes to mind:

1) Do you happen to have a log of the build or perhaps any error messages from it? An error message would help to identify the issue.

2) When you say they aren't showing up, do you mean in the app or have you also checked in your `dist/client/assets/images` folder for the images files? If the files are there but simply not showing up, it's most likely to be a CSS or HTML referencing issue. 

3) If you're on a Mac/*nix box, have you got your folder access settings configured correctly? Sometimes security settings can block scripts from touching your files. This could make sense if the rest of your build was created by yeoman but just your images aren't working because they were created by you with a different access policy.

**Comment by jspenc72** [comment]
I apologize I do not have a log. This issue was that the images were not copied into the dist/client folder when running grunt build. I am on a mac. There were no errors output. The only evidence was that the dist/client folder did not have a folder for the assets. 

The issue could have very likely been the permissions issue as you describe. I will see if I can replicate the issue and if so provide you instructions on how to do so.

In short here is what happened. 

1. Create git repo. 
2. Scaffold new project within the.git repo.
3. Sync repo with github
4. Another developer cloned the repo, added the image assets and pushed to origin.
5. I pulled the changes from the other developer which included the image assets. 
6. Everything displayed correctly when running grunt serve
7. No dist/client/assets/images folder was generated when running grunt build or grunt serve:dist

I reinstalled angular fullstack generator and rescaffold the project and added the images to the project by using the cp command at the terminal. This seems to have resolved the issue. 

Cheers!
