### ISSUE TITLE
PROBLEM with minimization for some .js files

### ISSUE THREAD

**Issue by JoelParke** [angular-fullstack/generator-angular-fullstack#1899]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 2.0.13 - but expect that is true of ALL
Node | x.x.x -- any
npm | x.x.x -- any
Operating System | Ubuntu 16.04 - but expect it to be OS independent

Item | Answer
----- | -----
Build Tool | Grunt serve:dist

IF a file such as **angular-timezone-selector.js** from bower install angular-timezone-selector does not end with a ';' then the minimized code breaks when loaded with:

    Uncaught TypeError:    angular.module(...).constant(...).constant(...).factory(...).factory(...).factory(...).directive(...) is not a function

The code should ERROR out perhaps!

**Comment by Awk34** [comment]
I don't think that's an issue with this generator. I don't think we ever included that dependency anyway. You should probably check with them about that, yeah?

**Comment by Koslun** [comment]
Either way it's actually not necessarily very likely that an error related to version 2.0.13  is still around in 3.7.x. 

If there actually was a general error with minifying dependencies that did not end with ";" then it likely was caused by a bug in the dependency we used to minify it in that version. Most dependencies have however been updated since then, AFAIK.

It should be pretty easy to test but think it then is very likely a bug with what we're using to minify.

But seems like a flaw in the dependency to not end with a ";", so like @Awk34 I'd head over and fix it at https://github.com/mishguruorg/angular-timezone-selector. If it hasn't already been fixed.

**Comment by JoelParke** [comment]
Thanks for the very quick response.  ? What do I need to update in the generator 2.0.13 so that I don't have this issue in the future.  I can't easily move to 3.x.  

Is there a guide on porting the Gruntfile to the new generator?

**Comment by Awk34** [comment]
As for the described 'minification' issue, I don't know what to tell you. I suggest giving full error details in a Stack Overflow question. 

As to guides on updating your Gruntfile from a 2.x.x version to the latest, there is no 'guide'. Questions about updating have been asked many times in the past: #185
