### ISSUE TITLE
Livereload on changing client scripts not working

### ISSUE THREAD

**Issue by Stalso** [angular-fullstack/generator-angular-fullstack#1929]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.3
Node | 4.4.4
npm | 3.9.3
Operating System | Windows 8.1
etc | etc

Item | Answer
----- | -----
Transpiler |  TypeScript
Markup |  Jade
CSS | LESS
Router |  ui-router
Build Tool |  Gulp
Client Tests |  Mocha
DB | MongoDB 
Auth | Y 
etc | etc

Hello. Browser livereload is not fired, when I change something in client scripts. But it works, when I change server scripts, or views.

The problem is in `watch `task. It watches: 

`gulp.watch(paths.client.scripts, ['lint:scripts:client', 'transpile:client']);`

But this tasks does not reload browser. They do not call `plugins.livereload` . If I place `plugins.livereload` in the end of  `transpile:client` task all scripts are reloaded. In fact, for every code change the whole client is transpiled, not only changed file. Is it normal? Why can not we transpile only changed files?

And when I try to write such code in `watch `task nothing happens. File even is not transpiled

     plugins.watch(paths.client.scripts)
        .pipe(plugins.plumber())
        .pipe(plugins.sourcemaps.init())
        .pipe(plugins.typescript()).js
        .pipe(plugins.sourcemaps.write('.'))
        .pipe(gulp.dest('.tmp'))
        .pipe(plugins.livereload());

**Comment by Koslun** [comment]
I have observed this in 3.5.x or 3.6.x as well. I.e. gulp typescript combo does not livereload properly.

Not completely sure how optimized the ts compilation is or if the typescript compiler or the gulp-wrapper around it have some limitations. I do believe there is some form of incremental compilation that is possible through gulp-typescript, see https://www.npmjs.com/package/gulp-typescript.

**Comment by Stalso** [comment]
But the problem is deeper. Maybe I need to create separate issue for it. As I mentioned, every change in client side code leads to full client transpiling. In fact, `watch` task rebuilds all client. Unfortunately, I am newbee in Node (I am .NET developer) and I can not overcome this by myself. Last thing i tried was to replace this: 

    gulp.watch(paths.client.scripts, ['lint:scripts:client', 'transpile:client:all:reload']);

with this:

    gulp.watch(paths.client.scripts, function(event) {
      console.log('File ' + event.path + ' was ' + event.type + ', running tasks...');    
      return gulp.src([event.path])
        .pipe(plugins.plumber())
        .pipe(lintClientScripts())
        .pipe(plugins.sourcemaps.init())
        .pipe(plugins.typescript()).js
        .pipe(plugins.sourcemaps.write('.'))
        .pipe(gulp.dest('.tmp'))
        .pipe(plugins.livereload());
      
    });

 I tried to transpile only one file. Changed file is transpiled and new version of file appears in `.tmp` folder, but even when I refresh browser manually, old code is loaded

**Comment by Awk34** [comment]
The way it's set up in the generator is the recommended way from `gulp-typescript`. Just adding `.pipe(plugins.livereload())` at the end of `transpile:client` might be your best bet.

**Comment by Stalso** [comment]
Thank you. But do you know, why do they recommend to transpile whole client for every change? Is not it shotgun approach?

**Comment by Awk34** [comment]
@Stalso I believe it's possible, but not with our current setup. Think about this regular JS ex:

`a.js`
```js
/**
 * @param {number} arg1
 * @param {number} arg2
 */
export function fn(arg1, arg2) {
  console.log(arg1 / arg2);
}
```
`b.js`
```js
import {fn} from './a';

fn(1, 1);
```
There's no definitions of types here, except for the JSDoc.

Here's the TS:
`a.ts`
```ts
export function fn(arg1: number, arg2: number) {
  console.log(arg1 / arg2);
}
```
`b.ts`
```ts
import {fn} from './a';

fn(1, 1);
```

Say we run this TS through gulp-typescript:
```js
let stream = gulp.src('lib/*.ts')
  .pipe(plugins.typescript());
```
`stream` here has two properties that are streams: `js` and `dts`, which out put `.js` code & `.d.ts` typings respectively. Right now the generator just uses `.pipe(plugins.typescript()).js` to get the `.js` stream and pipe it to our `.tmp` destination. This way, the TS compiler knows about all our files, and their typings, but the typings are never saved. If instead we saved typings for all our files as well, we would only rebuild the `.js` and `.d.ts`, since the compiler could know about the typings of our previously-transpiled files through the saved `.d.ts` files. I think.

**Comment by samsfisher** [comment]
I am using the latest version of generator 4.0.4

After gulp serve, the system compiles and i am able to see the webpage.

However, 'watch' is not working. if i change CSS or HTML i dont see the webpack/build system refreshing. 

I am using vagrant environment. I have 3000, 9000, 27017 forwarded as well. Dont know what the issue is.
