### ISSUE TITLE
Not able to start app on server

### ISSUE THREAD

**Issue by MarinAngelo** [angular-fullstack/generator-angular-fullstack#1958]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.5
Node | 4.2.6
npm | 3.6.0
Operating System Ubuntu 14.04

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | Stylus
Router | ui-router
Build Tool | Gulp
Client Tests | Jasmine
DB | MongoDB
Auth | Y 

Hi, I'm having problems with starting the app on the server with pm2, the app crashes and reports the following error: Cannot find module 'babel-runtime/core-js/set-immediate'
Shouldn't the dist version of the app be running without babel? 
After reding #501 I should maybe tell more about my deployment strategy. I use to deploy only the dist folder to my digitalOcean droplet and run my apps with pm2. This procedure worked perfect with version 2.1.1

**Comment by Koslun** [comment]
I believe it's a polyfill provided by babel for es6 functionality like promises: [babel polyfills](https://babeljs.io/docs/usage/polyfill/).

Not sure exactly what the problem is but...

- Have you set the `NODE_ENV` variable to 'production' (`export NODE_ENV=production`)?
- Tried clearing the npm cache, i.e. re-installing all the npm dependencies or just deleting node_modules and installing everything again?

**Comment by Awk34** [comment]
Built code uses the [Babel Runtime](https://babeljs.io/docs/plugins/transform-runtime/) on the server, which "Externalises references to helpers and builtins, automatically polyfilling your code without polluting globals.".

**Comment by MarinAngelo** [comment]
Thank you guys, after some npm updating, cache cleaning and running npm install with --productiion flag it works fine. :+1:
