### ISSUE TITLE
Deploy to heroku is not working using yo angular-fullstack:heroku

### ISSUE THREAD

**Issue by wikett** [angular-fullstack/generator-angular-fullstack#1966]
Item | Version
----- | -----
generator-angular-fullstack | 3.7.5
Node | 4.4.5
npm | 3.9.5
Operating System | Windows 7 

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML
CSS | SCSS
Router |  ui-router
Build Tool | Grunt
Client Tests | Jasmine
DB | MongoDB 
Auth | Y

Hello, I have just created my app, working perfectly in localhost but when I try to deploy to Heroku I have problems.

First of all, using ```yo angular-fullstack:heroku``` I get this error:
```(!) NamedBase constructor is deprecated. See https://github.com/yeoman/generator
/issues/882
? Name to deploy as (Leave blank for a random name):```

How can deploy into Heroku? must I wait when that issue it will be fixed?

I have tried to deploy manually, following the steps: [https://github.com/angular-fullstack/generator-angular-fullstack/issues/1920](url) [https://github.com/angular-fullstack/generator-angular-fullstack/issues/1950](url) but I can't get sorted.

After installing angular-fullstack, have I to create a heroku app?

1. cd dist
2. heroku create
3. git init
4. git add .
5. git commit -m "first commit"
6. git push heroku master
7. heroku open

Could you explain me the steps to create an app and deploy to heroku instead of using ```yo angular-fullstack:heroku``` ??

Thanks in advance

**Comment by AmirGilboa** [comment]
look at this:
https://github.com/angular-fullstack/generator-angular-fullstack/issues/1950

check the comment by djpark at the end, it might help you.

**Comment by savli** [comment]
I think your issue is that you are not linking a valid heroku app. In order for your remote to be connected to an application it needs be like follows `heroku git:remote -a desolate-ravine-67061`, instead of simply `heroku create`. So, the steps would be:

1. Go to heroku.com and declare your application manually. 
2. cd dist
3. add a git remote, which is connected to the app
4. git add .
5. git commit -m "first commit"
6. grunt buildcontrol:heroku 

Then, when you want to update the application 

1. cd ..
2. grunt build
3. cd dist
4. git add .
5. git commit -m "..."
6. grunt buildcontrol:heroku

That is what I have been doing and it works great!

**Comment by flaurian** [comment]
Here is the easiest workaround:

After yo has generated the app, go to heroku.com and create and application manually (ex. foo-bar-42424), then starting frome the root foolder run the following commands:

- grunt build
- cd dist
- heroku login (if you are not already authenticated)
- heroku git:remote -a foo-bar-42424
- cd ..
- grunt build (not sure if this one is necessary)
- grunt buildcontrol:heroku

Done

**Comment by jbradstreet** [comment]
Savli's approach worked for me, except for all the grunt commands. I attempted to follow the steps outlined in the "grunt build control" link mentioned [here](https://github.com/angular-fullstack/generator-angular-fullstack/blob/master/docs/generators/heroku.md)...still no luck. 

In the end I used "gulp" instead of "grunt" for all the commands and Savli listed, and it worked!

I still needed to connect my MongoDB, which wasn't straight forward. Couldn't leverage the generator commands, couldn't add it using Heroku's dashboard either. So I'll share how I did it.  

To connect MongoDB, I had to set up MongoLab through [mLab's website](https://mlab.com/). 
- Create a user with a password 
   - (save the password somewhere, you'll need it later when you go to your Heroku app dashboard)
- Copy the MongoDB URI they provide.
 
- Go to your Heroku dashboard.
- Select your app.
- Click on "Settings", then click "Reveal Config Vars."
  - Key = MONGODB_URI
  - Value = _paste in your copied uri from the mLab website_ 
       - Be sure to change the <dbuser> and <dbpassword> parts of the mLab uri with your created user and password. 

Hope this helps!

**Comment by rohita77** [comment]
flaurians instructions should be merged in the Read Me. ,d

**Comment by adyngom** [comment]
@flaurian steps should definitely be merged into Heroku readme. The confusing part is that you need to step out of dist and run the two last commands inside of root:
```
cd ..
grunt build
grunt buildcontrol:heroku
```

**Comment by tslmy** [comment]
how about using `gulp build`?
