### ISSUE TITLE
Using Lodash on client side

### ISSUE THREAD

**Issue by helgetan** [angular-fullstack/generator-angular-fullstack#2002]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.2
Node | 5.7.1
npm | 3.8.5

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML 
CSS | SCSS 
Router |  ui-router
Build Tool |  Gulp
Client Tests | Jasmine
DB | MongoDB 
Auth | Y 

Hey 
i'm trying to use lodash in my project, 
but i can't get it to work 

my steps:
`bower install lodash --save`
in my controller i add
`import _ from 'lodash';`

and in the constructor e.g. i add:
`console.log(_.assign({ 'a': 1 }));`

then i get this error 
`uncaught ReferenceError: require is not defined       // Line of import _ from 'lodash'`

**Comment by Awk34** [comment]
The 3.x.x version's of the generator use [Bower](https://bower.io/) as the front-end dependency manager. Lodash is [already included](https://github.com/angular-fullstack/generator-angular-fullstack/blob/3.7.2/templates/app/_bower.json#L17) as a front-end dependency. The wiredep gulp task should inject a script tag for lodash in your `index.html`. You can then use the global `_` object. You can't use `require` in a browser unless you use SystemJS/Webpack/Browserify.

**Comment by dbogda** [comment]
Thank you! I've been trying to figure out where Lodash gets loaded from and this helps the hunt. I don't like the aesthetic errors it's kicking during build but I'm trying to ignore them since they don't seem to impact functionality. 

I'm running version 4.1.1 and I don't have bower installed, are Lodash and other base dependencies now being loaded via webpack or gulp? I saw Lodash being imported in both tools and haven't traced them enough to figure out the sequencing and roles of each tool since they seem to overlap a little. 

I'm assuming the errors I have listed below are a result of the build script validating the .js before the dependencies get injected later? I started chasing my tail on this but figured it isn't broken so it doesn't need fixing, but I am curious and want to understand how this is all working.

/Users/Me/GitHub/afs/client/components/auth/auth.service.js
  118:19  error    '_' is not defined                                               no-undef
  148:20  error    '_' is not defined                                               no-undef
  161:16  error    '_' is not defined                                               no-undef
  174:29  error    '_' is not defined                                               no-undef
  188:22  error    '_' is not defined                                               no-undef

**Comment by Awk34** [comment]
@dbogda Lodash is included in the client code, the server code, *and* the gulpfile.

idk about those first four errors your have (empty string being undefined), but the last one is probably because your `client/components/auth/auth.service.js` doesn't have an `import _ from 'lodash';` at the top.

**Comment by dbogda** [comment]
@Awk34 Thanks again! I saw the use of _ in the client and server code but didn't see it import'd anywhere in the default scaffold, I figured magic until I read this thread.

I'm not sure what happened to the formatting on paste, all 5x were '_' lodash errors related to the import, and are all resolved via the `import _ from 'lodash';`.  I didn't want to unnecessarily bloat my modules with redundant code if it wasn't needed but I do prefer the clean build and explicit declarations. Thanks!

**Comment by dbogda** [comment]
Correction! I see it listed in client/components/socket/socket.service.js & server/config/environment/index.js, just not where I expected it.

**Comment by Awk34** [comment]
@dbogda the reason that using lodash in a file that hasn't imported it on the client works in the 4.x.x+ versions of the generator, is because if you just `import`/`require` lodash once, it will by default set `window._` to be an instance of lodash. This is something that can be disabled, or wouldn't happen it all if you only used `lodash-es` from npm.
