### ISSUE TITLE
Any reason not allowing late function declaration by default?

### ISSUE THREAD

**Issue by nabilzhafri** [angular-fullstack/generator-angular-fullstack#2010]
See here:
John papa's styling guide:
[https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md)

By default, JSHint gives me warning when doing late function declaration:
`'MainSidebarController' was used before it was defined.`

The best practice suggests to use late function declaration for readability:

>  Placing the implementation details of a function later in the file moves that complexity out of view so you can see the important stuff up top.

> Function declarations are hoisted so there are no concerns over using a function before it is defined (as there would be with function expressions).

So the suggestion here is to update .jshintrc to allow late function definition instead:
`"latedef": "nofunc"`

But I'm sure you guys have your own reason?

**Comment by Awk34** [comment]
It's really more of a personal preference I think. Since functions are hoisted, you can declare them anywhere in the same closure. Some people believe it's better to keep their definition before their use. This *does* make more immediate sense, especially if your're unfamiliar with JS hoisting.

Either way, I don't think we'll be changing too much of the JSHint rules. The 4.0.0 beta uses ESLint / TSLint instead.

**Comment by nabilzhafri** [comment]
@Awk34 Understand. Not really an issue though, just wanna see the reason behind it. Your reason does make sense. Thanks for your quick answer!
