### ISSUE TITLE
Bootstrap.js is excluded by default

### ISSUE THREAD

**Issue by nabilzhafri** [angular-fullstack/generator-angular-fullstack#2011]
Took me a while to find this, but seems like the `gulpfile.bibel.js` has been configured such that it excludes `bootstrap.js` by default.

What is the reason it excludes `/bootstrap.js/` by default considering bootstrap is a foundational library for fullstack?

![image](https://cloud.githubusercontent.com/assets/6986883/16269053/63cc029e-38c3-11e6-922c-1f74b7a6daf1.png)

**Comment by Awk34** [comment]
As you can see [here](https://github.com/angular-fullstack/generator-angular-fullstack/blob/3.7.5/templates/app/gulpfile.babel(gulp).js#L514-L515), `bootstrap.js` is only included in the `exclude` block when [UI Bootstrap](https://github.com/angular-ui/bootstrap) is chosen. If you chose UI Bootstrap, you'll want to use those components instead of the vanilla Bootstrap ones.

**Comment by nabilzhafri** [comment]
Ah I see it now. So it depends on my selection when I generate the template. Thanks!
