### ISSUE TITLE
Gitter.im support chat / enhancing the documentation

### ISSUE THREAD

**Issue by cguckes** [angular-fullstack/generator-angular-fullstack#2100]
Using this generator, I constantly run into best-practise questions I can't seem to get an answer to via googling. Would you kindly consider setting up a gitter.im to allow the users to discuss issues and maybe compile an FAQ / expand the README.md with requested information? I'd be happy to contribute to enhancing the documentation once I understand this stuff better.

**Comment by atodicebear** [comment]
Gitter.im is allready set up.
https://gitter.im/angular-fullstack/generator-angular-fullstack
For FAQ/or Tutorials to some things with the Generator in Generell I didnt found myself.
Searching here through Issues from others oder doing workarounds.
Would be great if someone would do a Proper Guide/Tutorial.
Since its getting more and more Popular, with SEAN possibility even more now.

**Comment by Awk34** [comment]
There is already a Gitter.im badge in the readme, and I have been working on more documentation for this project.
