### ISSUE TITLE
jquery removed?

### ISSUE THREAD

**Issue by netfu92** [angular-fullstack/generator-angular-fullstack#2214]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Why jquery was removed? Bootstrap needs jquery, why remove it?

I installed it manually, how can I make sure it is added to my application?

Thanks.

**Comment by Awk34** [comment]
Nothing that the generator supports out-of-the-box requires JQuery. Angular includes it's own lite implementation of a JQuery API, and the Bootstrap JS is never used in an immediately-scaffolded project (since we give you the option to use angular-ui-bootstrap). 

Simply `npm install --save jquery` and `import`/`require` it.
