### ISSUE TITLE
Error: [$compile:tpload]...

### ISSUE THREAD

**Issue by MarinAngelo** [angular-fullstack/generator-angular-fullstack#2281]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.5
Node | x.x.x
npm | x.x.x
Operating System | OS X 10 / Windows 10 / Ubuntu 15.10 / etc
etc | etc

Item | Answer
----- | -----
Transpiler | Babel
Markup | HTML
CSS | CSS / LESS / SCSS / Stylus
Router | ui-router
Client Tests | Jasmine / Mocha
DB | MongoDB / SQL
Auth | Y / N
etc | etc

Hi there, 

After building my app and running it with gulp serve:dist I receive the following error in the browser console:

Error: [$compile:tpload] Failed to load template: components/navbar/navbar.html (HTTP status: 404 Not Found)...etc

In dev-mode the app works fine.

**Comment by Awk34** [comment]
The build process uses [gulp-angular-templatecache](https://github.com/miickel/gulp-angular-templatecache), which bundles all your HTML files as text into a `templates.js` file. Inside there, the text is added to Angular's template cache, so that when your views ask for a template, your app doesn't have to go out to the net to get them; they're already in the code, cached.

What are the contents of your `.tmp/` folder? Do you see the `templates.js` file? Maybe confirm that this file is getting added to your app js in the `dist` folder

**Comment by MarinAngelo** [comment]
In the .temp/ folder I have: app, components, cosmicjs-node-master, templates.js, but in the dist folder I can't find a templates.js file.

**Comment by MarinAngelo** [comment]
Problem solved, it has been the dependency folder "cosmicjs-node-master" at the wrong place. Thanks for your help!
