### ISSUE TITLE
Add documentation for deploying by hand?

### ISSUE THREAD

**Issue by mxtetrachord** [angular-fullstack/generator-angular-fullstack#2366]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Would it be possible to get deployment instructions for those who don't/can't use Heroku or Openshift in the docs? I'm trying to deploy right now to Ubuntu 16.04 using Apache, and I'd gladly PR back in with stuff I've learned provided I can successfully stand up the app.

If not, is there a blessed path for deploying from a vanilla VPS?

**Comment by Azayzel** [comment]
I say go for it. The more information we can put out there the better. This generator didnt have a Windows/ IIS deployment doc so I created it.  Go for it man.

**Comment by Awk34** [comment]
I'd say the steps are:

1. Push to your deployable branch
2. Assert tests pass
3. SSH into your server
4. Run a build
5. Run `NODE_ENV=production node ./dist/server`

That is probably the most basic form of manual deployment.

**Comment by JoshiAsha** [comment]
Hi @Awk34 ,

I tried to deploy my project on a linux machine and I am getting the error mentioned below.
It it difficult to understand what is missing because the documentation for deploying the angular full-stack project is not much detailed.
I have added the issue under the following link: [https://github.com/angular-fullstack/generator-angular-fullstack/issues/2667]
`module.js:471`
    `throw err;`
    `^`

`Error: Cannot find module './build/bindings/iltorb.node'`
    `at Function.Module._resolveFilename (module.js:469:15)`
    `at Function.Module._load (module.js:417:25)`
    `at Module.require (module.js:497:17)`
    `at require (internal/module.js:20:19)`
    `at Object.<anonymous> (/home/asha/Downloads/dist/node_modules/iltorb/index.js:10:16)`
    `at Module._compile (module.js:570:32)`
    `at Object.Module._extensions..js (module.js:579:10)`
    `at Module.load (module.js:487:32)`
    `at tryModuleLoad (module.js:446:12)`
    `at Function.Module._load (module.js:438:3)`
