### ISSUE TITLE
Travis CI test fails for clean Angular Generator Project

### ISSUE THREAD

**Issue by awwong1** [angular-fullstack/generator-angular-fullstack#2367]
Travis CI Builds broken for newly generated projects?

[TravisCI Job Log](https://travis-ci.org/udia-software/udia/jobs/179150183)

Specifically, `npm install` fails on TravisCI.
Running tests locally work fine.

I tried changing node versions from `4.4.6`, `6.9.1`, `7.2.0` but that didn't seem to do anything.

 - [X] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 4.1.0
Node | 6.9.1
npm | 3.10.8
TravisCI Default

**Comment by Awk34** [comment]
It looks like your build is failing because [iltorb](https://github.com/MayhemYDG/iltorb) fails to build. Make sure your build machine has all of the proper [node-gyp](https://github.com/nodejs/node-gyp) build tools. If you don't care about using brotli compression, you can swap `shrink-ray` for `compression` Express middleware.
