### ISSUE TITLE
Upgrade project from 3.7.6 to 4.2

### ISSUE THREAD

**Issue by aabm00** [angular-fullstack/generator-angular-fullstack#2560]
- [ ] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | 3.7.6
Node | 6.9.2
npm | 3.10.9
Operating System | Windows 7 

Item | Answer
----- | -----
Transpiler | TypeScript
Markup | HTML 
CSS | CSS 
Router |  ui-router
Client Tests | Jasmine 
DB | MongoDB 
Auth | Y 
socket.io

I am working in a project started with the version 3.7.6. I know that it's posible to upgrade a project from one version to other scaffolding out over the project again following the comments in the  [link](http://stackoverflow.com/questions/18480316/how-to-upgrade-existing-project-scaffolded-with-yeoman), but I supose it can't be done with mayor releases as 3.x.x to 4.x.x.

There is an easy way to do it?

Thanks

**Comment by Awk34** [comment]
Doing what Sindre suggests there is probably your best option. I believe this has been covered in a bunch of previous issues as well. The nature of this kind of project makes it very difficult for end-users to upgrade, since this is a source-code generating project, and when we change the source code that it generates, we have no idea of knowing what kinds of changes end users make to their own generated code. I'd say either re-scaffold on top of your current app and look at the diff, or scaffold a completely new app and incrementally pull features into your current app that you want.

**Comment by aabm00** [comment]
Thanks!!!



2017-05-10 19:01 GMT+02:00 Andrew Koroluk <notifications@github.com>:
