### ISSUE TITLE
Doubt about design using yeoman.

### ISSUE THREAD

**Issue by jansilva** [angular-fullstack/generator-angular-fullstack#2663]
Hi everyone! How are you? I hope you are fine. My English is rust, but it is a working in progress.
I have a design question here. I didn't find another place to post it, like mail list or forum. So excuse me for this post.

We have here a project generated by yeoman, and I need to add some support for heap analytics. I found how to do it. However, I need to split client development setting and production setting for heap analytics. The whole file is the same for both, except by an Id argument. Like this:

```
<script type="text/javascript">
    window.heap=window.heap||[],heap.load=function(e,t){window.heap.appid=e,window.heap.config=t=t||{};var r=t.forceSSL||"https:"===document.location.protocol,a=document.createElement("script");a.type="text/javascript",a.async=!0,a.src=(r?"https:":"http:")+"//cdn.heapanalytics.com/js/heap-"+e+".js";var n=document.getElementsByTagName("script")[0];n.parentNode.insertBefore(a,n);for(var o=function(e){return function(){heap.push([e].concat(Array.prototype.slice.call(arguments,0)))}},p=["addEventProperties","addUserProperties","clearEventProperties","identify","removeEventProperty","setEventProperties","track","unsetEventProperty"],c=0;c<p.length;c++)heap[p[c]]=o(p[c])};
    
  heap.load(ID); // Here we put id for production or development.
</script>
```
In this line of the script: heap.load(ID); // Here we put id for production or development.

So, my first approach was to create two diferent files and put a condition inside my webpack to identify current environment and add correct file into vendor.js. But I do not know if this is the best way to do that. Anyone can help me?

Best Regards
Jan Palach

**Comment by Awk34** [comment]
Would you reformat your code? Surround it with \`\`\` for formatting: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by Awk34** [comment]
I think I see. You're creating a heap, and then using different IDs for dev/prod in your `heap.load(ID)`.

It's generally not advised to directly add code using a script tag, but if you really need to, the main HTML template file is rendered by Webpack using the [html-webpack-plugin](https://github.com/jantimon/html-webpack-plugin/), which supports lodash templates (similar to what we use to render the project files for this generator). See https://github.com/jantimon/html-webpack-plugin/#writing-your-own-templates.

Otherwise, I'd suggest creating a new `.js` file with this code and `import`ing it in maybe your client `app.js`. Then it'd be easy to choose the ID:

```js
const id = process.env.NODE_ENV === 'development'
  ? '1234'
  : process.env.NODE_ENV === 'production'
  ? '5678'
  : '9012';
heap.load(id);
```

**Comment by Awk34** [comment]
I hope this has answered your question. If not, please reach out on Stack Overflow or our Gitter.im channel

**Comment by jansilva** [comment]
It was a good answer, the first tip should be the better way. Thanks!
