### ISSUE TITLE
Cannot deploy angular full-stack project 

### ISSUE THREAD

**Issue by JoshiAsha** [angular-fullstack/generator-angular-fullstack#2667]
Hi, 
I tried to build and deploy the auto-generated angular full-stack project on a Linux machine. 
I have only git, nodejs and python installed on my machine.
When I ran this `$ NODE_ENV=production node ./server` command (https://angular-fullstack.github.io/deployment/), I am getting an error `cannot` find module 'module './build/bindings/iltorb.node'`
Did I miss anything?

Below are the details of my Linux machine and the angular-full-stack generator I used.
generator-angular-fullstack | 4.2.2
Node | 6.12.0
npm | 3.10.10
Operating System | Ubuntu 16.4

error log on running `npm install`: 
[npm-debug.log](https://github.com/angular-fullstack/generator-angular-fullstack/files/1474188/npm-debug.log)

package.json file
[package.json](https://github.com/angular-fullstack/generator-angular-fullstack/files/1476089/package.txt)
 
It would be great if somebody could help

Thank you.

**Comment by Awk34** [comment]
@JoshiAsha the issue comes from a compression library called `shrink-ray`, which depends on `iltorb` for Brotli compression. I've switched the generator back to using the regular `compression` library from Express (see https://github.com/angular-fullstack/generator-angular-fullstack/commit/e9f895d5ade1007f6a01f78af6c312114a4adf5c) since many users like yourself were having issues compiling `iltorb`. Just replace `shrink-ray` with `compression` in your `package.json` and `server/config/express.js` files.
