### ISSUE TITLE
Will not install on Windows 10 Pro

### ISSUE THREAD

**Issue by nigel-dewar** [angular-fullstack/generator-angular-fullstack#2672]
- [x] I understand that GitHub issues are not for tech support, but for questions specific to this generator, bug reports, and feature requests.

Item | Version
----- | -----
generator-angular-fullstack | x.x.x
Node | 8.9.0
npm | 3.10.5
Operating System |  Windows 10 

Item | Answer
----- | -----
Transpiler | Babel 
Markup | HTML/ Pug
CSS 
ui-router
Client Tests Mocha
DB | MongoDB 
Auth | Y 
Socket.IO | Y

I have installed the necessary bits for windows to run node-gyp stuff. C++ build tools, I have Visual Studio 2015 installed, plus Python 2.7. Run the command to tell node to use VS 2015 etc, and am able to npm install node-gyp which builds sucessfully, so not issues there. I also run a CMD prompt in Admin user to ensure full power.

However I cannot install this yo.

![image](https://user-images.githubusercontent.com/9402456/33308302-a1cf271c-d465-11e7-84bd-2342d89b5f3b.png)

Is there something special one needs to do to get this thing installed?

**Comment by CorentinDy** [comment]
wow such an old npm version , maybe update everything to last stable version, at least npm , clean and reinstall .
you should be at least a 5.5.1 for npm

**Comment by nigel-dewar** [comment]
Ok thanks ill try this. I didnt know my npm was old.. cheers for heads up.

**Comment by nigel-dewar** [comment]
Updated to NPM 5.5.1

after a couple of hours of stuffing around, I removed shrinkray from the packages.json and express config. I just cant get it to work on windows machine.

node-gyp etc builds just fine, but this thing. nup.

Hope this helps others on windows machines struggling with this and saves them time.

**Comment by CorentinDy** [comment]
Well ok , you are not supposed to remove package from packages.json, did you check what it does and if remove it didn't broke anything ?

**Comment by nigel-dewar** [comment]
The only way to get this thing to run was to remove shrinkRay. Nothings broken. all is running. prob maybe it will be slower than norm maybe, because I assume shrinkray does some kind of compression, however this was was not a deal breaker for me, I just wanted to see how the stack runs.

**Comment by CorentinDy** [comment]
I just build from scratch the projet and for me it work perfectly without removing anything , on W10 pro too , maybe last update on canary branch resolve this ?

**Comment by nigel-dewar** [comment]
Ok thank you for heads up.

In the last hour or so I completely reinstalled node, npm, did an npm clean cache etc. So I'll give this another shot, because obviously its my damn dodgy config since your getting job in W10 pro.

Cheers mate.

**Comment by Awk34** [comment]
`shrink-ray` has been removed since `5.0.0-beta.1`, and more recently `4.2.3`. It's a nice-to-have, but so many others have had issues compiling it on Windows that it was decided to switch back to the regular `compression` library.

I've never had any issues installing it on Linux boxes, but I *have* seen failures on Windows.

**Comment by hoogw** [comment]
I have same error, the problem is your node version is too high. 
node-inspector, node-gyp do NOT like node version >= 6.3
because node >= 6.3 will have its own debugger.

You must downgrade your node version to 5.6.0
If you on windows, use [nvm-windows](https://github.com/coreybutler/nvm-windows) allow you run multiple version of node on windows.

This solved my problem, all the error are gone.
