### ISSUE TITLE
Get the currentUser at serve side [question]

### ISSUE THREAD

**Issue by nikhil-bhandari** [angular-fullstack/generator-angular-fullstack#459]
I was going through the auth.service.js and it seems that auth.isAuthenticated() injects the current user to the request if the user is logged in.

So current user can be accessed but the endpoint has to be restricted to logged in user.

Now, I have an endpoint that can be accessed publicly, but if a user is logged in I want to manipulate the results in some manner (Login is optional).

Any suggestions on achieving this?

**Comment by azachar** [comment]
@bhagwat thanks for your posting. It works!

I have an another related question, how do I use it with ``express params``?

```js
router.param('user', controller.populateUserFieldsBasedOnRole);
router.get('/:user', auth.addUserIfAuthenticated(), controller.show);
```
the problem is that auth.addUserIfAuthenticated is executed after ``router.param`` so the param function is not aware of any ``req.user``, do you have any idea how to make work nicely?

Thanks!
