### ISSUE TITLE
Suggestion: description meta tag should be accessible to angular

### ISSUE THREAD

**Issue by simonh1000** [angular-fullstack/generator-angular-fullstack#537]
By default the generator places the ng-app statement on the body tag, which means that it is not possible to update `<meta description-...>` dynamically.  With Google now able to process some javascript, I think this could be useful to be able to control

**Comment by wikett** [comment]
@kingcody I´ve used your approach and it works perfectly. Google indexed all my pages with its title and meta description properly.

The problem that I have now is when I try to share on page on Facebook because Facebook doesn´t run javascript before to post it. The only solution is using something like https://prerender.io/ ???

my website is www.subexpuesta.com (it´s only in spanish but I want to translate it)
