### ISSUE TITLE
Q: "node app.js" doesn't work after "grunt build" command

### ISSUE THREAD

**Issue by mescalito** [angular-fullstack/generator-angular-fullstack#590]
thanks for your time! I'm new using yeoman so i don't know what is exactly going on .

When using the `grunt build` command everything seems to works fine and the "**/dist**" folder is generated ok, but why the `node app.js` command doesn't fully work inside the "**/dist/server**" folder?

To make my app working on the "**/dist**" folder I have to open file app.js and then in like no.8 change 'development' into 'production'

File app.js line no.8

``` javascript
process.env.NODE_ENV = process.env.NODE_ENV || 'development'; // change 'development' to 'production'
```
- Do I need to do make that change every time I plan to deploy to the server?

After digging into the grunt.js I realized I can run this command `grunt serve:dist` and then the server seems to work fine, but obviously I won't have that option into my production server, I just want the "**/dist**" folder.
- What am I doing wrong? and how can I run my project from the "**/dist**" folder on my production server?

**Comment by Tom2277** [comment]
I just can't figure out how to get the app to set environment variables in production mode.  

I've read a lot here and tried a lot.   Somehow editing my .bash_profile (or something else?) managed to set my FACEBOOK_ID and secret to their api keys, and the NODE_ENV to production using a bash method described in #501 but the same method doesn't work for TWITTER_CONSUMER_ID or DOMAIN... (although somehow my app seems to be getting the domain accurately in another way).  IF I hard code my Twitter API's into the ./config/environment/index section as the default value, my Twitter Oauth is working pretty well.

I'm just not sure what I'm missing ... I tried using require('.config/local.env') at the beginning of app.js as kingcody suggested in #513 but it didn't work.

I guess I'd just like to be able to set api keys and stuff from a .env file .  I'm fairly(very) clueless on what happens if a web site starts getting traffic and requires multiple instances and unsure about whether I should be setting environment variables for each instance vih bash or shel or etc or if having them in a file (not tracked on a cloud git repo) is better ??

Thanks for any help.  FWIW ,  I'm grateful for the generous work you guys have shared with AFS . I'm also satisfied enough with creating a production dist file with grunt serve:dist on my laptop and then cutting and pasting the files into a local "dist"-only repo where I can edit a few things then push.  (I bet I could get rid of a lot of dev dependencies that are still getting included in dist huh? )
