### ISSUE TITLE
Authorization problems

### ISSUE THREAD

**Issue by sarunast** [angular-fullstack/generator-angular-fullstack#630]
Hi, I have this problem with passport authorisation whenever use 'connect with facebook' the app logs me in. It saves all the data to mongoDB, however when I try access for example this route `router.get('/me', auth.isAuthenticated(), controller.me);` i always get this:

`UnauthorizedError: No Authorization header was found`

This happens with all the passport strategies including local.

---

Sorry I am fairly new to nodejs environment and I didn't knew where to ask this kind of question. So just directing me to the right documentation would be helpful or where to look for answers.

**Comment by uiktiomasfeliz** [comment]
And how you fix it?

**Comment by Stamy** [comment]
You don't fix it, it is done by design like this.
If you you are passing page directly you will get that error 'UnauthorizedError: No Authorization header was found'. Which means that you are not including your JWT token in app and you are not recognised.  If you do this via angular application it will handle all all requests for you which will attach the Header (JWT) just inspect web developer tools and you will see. So if you want to access page directly copy the header and pass it manually.

P.S. This was at the time I was using the generator, I don't know how it changed and how it works now.

**Comment by uiktiomasfeliz** [comment]
Thanks for answer!
