### ISSUE TITLE
ESLint support

### ISSUE THREAD

**Issue by sigriston** [angular-fullstack/generator-angular-fullstack#652]
Hi folks,

I'm a fan of ESLint & have modified a couple of my fullstack projects to use it instead of JSHint. Do you all think it would be cool to either switch to ESLint or at least offer it as an option?

Let me know, this is also something I'm considering contributing a PR for.
Thanks all once more for the great project! :+1:

**Comment by Koslun** [comment]
Been a long time in the JS world since the start of this issue and Esprima does now seem to support ES6 (see http://esprima.org/), so would conversely figure that ESlint now supports ES6/ES2015. Don't think any of the pros with ESlint have faded but might be more relevant to compare it to TypeScript and TSlint.

**Comment by aendrew** [comment]
ESLint is definitely becoming the de-facto standard for linting ES2015 (if it's not already). It would be really nice to use that instead of jsHint for Babel projects.

**Comment by riyadhalnur** [comment]
As it stands now, this generator uses `jscsrc` which has merged with ESLint recently. There's no reason now not to switch to ESLint. I'm using ESLint with this generator. I can open a PR for this if needed.

**Comment by Awk34** [comment]
@riyadhalnur 4.0.0 will ditch JSHint & JSCS in leu of using ESLint
