### ISSUE TITLE
Upload development database to openshift/heroku

### ISSUE THREAD

**Issue by TWKDreamState** [angular-fullstack/generator-angular-fullstack#736]
Is there a way to automate the upload of the local development database to the production database or to seed the production database?

**Comment by tomascharad** [comment]
@TWKDreamState, Could you please introduce me your seeding methodology?
I'm trying to seed the production DB. I've tried multiple ways (grunt, seed.js) but I don't seem to find a proper way tu running a seeding task.

The seed.js file I think was made for automatic seeding for demo purposes, while I'm looking something more related to a 'Rails rake task', something like: grunt seed (Which I implemented, but the grunt file is not copied to the dist folder.

I have to seed more than 6GB to my DB so that's why I want to have a bit more of control of what is happening.

Thanks!

**Comment by Awk34** [comment]
For that size of data, I recommend using something like `mondodump` and `mongorestore` (assuming you're using mongo)

**Comment by tomascharad** [comment]
@Awk34 I have to parse 6 (1GB each aprox.) .txt files... I'm creating rows line by line, would mongodump and mongorestore apply to this?

**Comment by Awk34** [comment]
Hmm, maybe more so `mongoimport`. That's exactly what it's designed for.
